trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  imageName: 'dotnet-album-viewer'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: docker/app/Dockerfile